### ISSUE TITLE
class_6.ipynb 无法运行

### ISSUE THREAD

**Issue by BoseSean** [tsycnh/Keras-Tutorials#1]
十分感谢 @tsycnh 做出详细易懂的教程。
在运行```class_6.ipynb```的时候我遇到了如下error：
```
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/keras/utils/data_utils.py", line 578, in get
    inputs = self.queue.get(block=True).get()
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/usr/lib64/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib64/python3.6/site-packages/keras/utils/data_utils.py", line 401, in get_index
    return _SHARED_SEQUENCES[uid][i]
  File "/usr/lib64/python3.6/site-packages/keras/preprocessing/image.py", line 825, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)
  File "/usr/lib64/python3.6/site-packages/keras/preprocessing/image.py", line 1233, in _get_batches_of_transformed_samples
    img = self.image_data_generator.preprocessing_function(img)
  File "/usr/lib64/python3.6/site-packages/keras/applications/inception_v3.py", line 407, in preprocess_input
    return imagenet_utils.preprocess_input(x, mode='tf')
  File "/usr/lib64/python3.6/site-packages/keras/applications/imagenet_utils.py", line 178, in preprocess_input
    mode=mode)
  File "/usr/lib64/python3.6/site-packages/keras/applications/imagenet_utils.py", line 115, in _preprocess_symbolic_input
    x /= 127.5
TypeError: unsupported operand type(s) for /=: 'JpegImageFile' and 'float'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "test_train.py", line 68, in <module>
    class_weight='auto'
  File "/usr/lib64/python3.6/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/keras/engine/training.py", line 2192, in fit_generator
    generator_output = next(output_generator)
  File "/usr/lib64/python3.6/site-packages/keras/utils/data_utils.py", line 584, in get
    six.raise_from(StopIteration(e), e)
  File "<string>", line 3, in raise_from
StopIteration: unsupported operand type(s) for /=: 'JpegImageFile' and 'float'
```

Environment:
```
Pillow (5.0.0)
Keras (2.1.5)
numpy (1.13.3)
tensorflow-gpu (1.6.0)
Python 3.6.4
Nvidia driver: 387.26   
CUDA 9.0
```

**Comment by tsycnh** [comment]
@BoseSean 我重新跑了一下这个代码，确实有这个问题。估计也是代码发布太久了，好多库更新，导致一些不兼容，在[我的博客上](https://blog.csdn.net/tsyccnh/article/details/78889838#comments)  zbh11808给出了一个解决方案，但是需要改keras库，着急的同学可以按这个方法改。我再看看有没有其他不需要改库代码的方法。

**Comment by tsycnh** [comment]
发现问题了，目前keras最新版是2.1.5版本，有bug。将keras切换成2.1.2版本即可。而且似乎下一个版本（2.1.6 ?）已经将该bug修复了,等出来了可以试一试。
